---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ratings
spec:
  targets:
    - name: ratings
      ports:
        - number: 9080
  peers:
    - mtls:
        mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings
spec:
  host: "ratings.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
